# This is a basic workflow to help you get started with Actions
name: Show in the Actions tab

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Click in action tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Sample Build 81191"
    # The type of runner that the job will run on  #  ubuntu-latest windows
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: Checkout the repository
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo job run successfully

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git -v,
          git log.
          git branch -a