name: Run with secret

# generate a github action yml that can run every minute
on:
  workflow_dispatch:
  
env:
  API_CSPROJ_PATH: "./src/Api/Api.csproj"
  API_VERSION: "1.0.0"
  API_NAME: "Api"
  MY_HOME: "${{ github.workspace }}"


jobs:
  build:
    name: "Run with secret"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: dotnet --info
      - name: Run a multi-line script
        run: |
          echo "$API_NAME"
          echo "$API_CSPROJ_PATH"
          echo "${{ secrets.SENDER }}"
          echo "${{ secrets.PASSWORD }}"